name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install .Net Core
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: 6.0.203
      - name: Install dotnet-script
        run: dotnet tool install dotnet-script --global

      - name: Run build script
        run: dotnet-script build/build.csx
        env: # Or as an environment variable
          GITHUB_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IS_SECURE_BUILDENVIRONMENT: ${{ secrets.IS_SECURE_BUILDENVIRONMENT }}
          MARKETPLACE_ACCESSTOKEN: ${{ secrets.MARKETPLACE_ACCESSTOKEN }}
